### ISSUE TITLE
Need example of valid DCEConfig.yaml

### ISSUE THREAD

**Issue by greenozon** [Luca1991/DiscCheckEmu#17]
I tried to create a sample config file
but whatever I tried lead to yaml errors....

eg

![image](https://github.com/Luca1991/DiscCheckEmu/assets/765343/d6923c05-377d-4baa-9c94-53f1d322f713)

lead to

![image](https://github.com/Luca1991/DiscCheckEmu/assets/765343/d24fd24c-d699-4f8c-9594-80137535f65a)

is it possible to include a valid parse-able samples of at least one config yaml into repo please?

**Comment by Luca1991** [comment]
Hi @greenozon 
the indentation of your yaml file looks wrong!
You can find working examples in [ConfigurationDocumentation.md](https://github.com/Luca1991/DiscCheckEmu/blob/main/ConfigurationDocumentation.md) file.
For example:
```
loader:
  target: "AG.exe" 

virtual_drives: ['L']

hooks:
  - api: "GetDriveTypeA"
    arg1: "L:\\"
    return: 5 # DRIVE_CDROM
  - api: "GetVolumeInformationA"
    arg1: "L:\\"
    arg2: "AWESOME_GAME"
    return: true
```

You can use one of many free web-based tools to check the syntax of your yaml file, for example: https://yamlchecker.com/

Please let me know if this solves your issue, otherwise feel free to add a new comment :)
